### PR TITLE
sdk-cpp: Recipe parse fixes

### PR DESCRIPTION
**Pull request by codrin989**
Signed-off-by: Codrin Ciubotariu <codrin.ciubotariu@microchip.com>

*Issue #, if available:*

*Description of changes:* Some fixes for the aws-iot-device-sdk-cpp-v2 recipe. aws-iot-device-sdk-v2.inc is still missing though.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rpcme** [comment]
I didn't realize this got pulled up with the other zeus branch fixes. Apologies! I really need to get that CI harness running.

**Comment by codrin989** [comment]
No problem. I think that zeus has the same issues.

**Comment by codrin989** [comment]
Hi @rpcme , could you please tell me when you think this recipe will be fixed? At this moment, all the builds fail at parsing because aws-iot-device-sdk-v2.inc is missing, even if we don't use the recipe.

**Comment by rpcme** [comment]
@codrin989 I have now removed the file on master and the zeus branch.

**Comment by codrin989** [comment]
Thanks a lot!

**Comment by rpcme** [comment]
No worries and sorry for that.  I thought it would be done by now but customer engagements are priority Which has caused the delay here. Thank you for the understanding.  Hopefully, soon, we will no longer get surprises like this.

On Apr 3, 2020, at 06:00, Codrin Ciubotariu <notifications@github.com> wrote:

﻿


Thanks a lot!

**Comment by codrin989** [comment]
No problem. Everything seems fine now. Thank you for your fast replies!

**Pull request merged**
