### PR TITLE
Add aws-iot-fleetwise-edge recipe

### PR DESCRIPTION
**Pull request by hefroy**
*Description of changes:*
- Adds aws-iot-fleetwise-edge recipe

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by hefroy** [comment]
Should add a README.md to explain about modifying the config.json file with suitable values.

**Comment by rpcme** [comment]
@hefroy I am curious why the layer compat is Gatesgarth - is this due to a specific BSP you're targeting? If really it's only gatesgarth then the PR needs to be to gatesgarth-next branch.  We can discuss offline. @nateglims can also discuss.

**Comment by hefroy** [comment]
IoT FleetWise edge repo is now public: https://github.com/aws/aws-iot-fleetwise-edge
Commit updated to reflect this and WIP status removed.

> Should add a README.md to explain about modifying the config.json file with suitable values.
Done

> @hefroy I am curious why we target Gatesgarth - is this due to a specific BSP you're targeting? If really it's only gatesgarth then the PR needs to be to gatesgarth-next branch. We can discuss offline. @nateglims can also discuss.
Yes as discussed this is due to us targeting the NXP S32G BSP. I've changed the base branch to `gatesgarth-next`.

**Pull request closed without merging**
