### PR TITLE
Add Amazon CloudWatch Publisher

### PR DESCRIPTION
**Pull request by mkozjak**
The aim of this PR is to add support for [amazon-cloudwatch-publisher](https://github.com/awslabs/amazon-cloudwatch-publisher).
There's still work to do on this and certain decisions to make. This implementation works for my use-case, but there's things that need to get optimized. PR reviews would be desirable.

Namely:

- dependencies with inexistent recipes, like `python3-boto3` and `python3-timeloop`
- `LAYERSERIES_COMPAT_meta-aws` poky warrior inclusion
- user and group `cwpublisher` and `wheel` inclusion
- destination files and directories organization

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rpcme** [comment]
@mkozjak Sorry for the delay, I have been on leave.

Really nice contribution - thank you!

We cannot change the compatible here because prior to zeus a different gtest package name was used in oe.  This caused build break for one of the SageMaker NEO recipes.   

I suggest this approach.  When I get to my desk, I will make a warrior branch.  When your PR removes the LAYERSERIES_COMPAT change, I will accept the PR and pull down the commit to the freshly to-be-minted warrior branch.

Hopefully this works for you?

**Comment by mkozjak** [comment]
@rpcme, that'd be good enough, yes! I did some cleanups.

**Comment by rpcme** [comment]
Thank you for your contribution!

**Comment by mkozjak** [comment]
@rpcme please notify me when this gets into warrior. I see it wasn’t merged.

**Comment by rpcme** [comment]
Somehow I don't know why that happened @mkozjak it was not my intent.  It's done now.

**Pull request merged**
