### PR TITLE
scikit-learn, scipy and shapely packages

### PR DESCRIPTION
**Pull request by srikanth311**
*Issue #, if available:*

*Description of changes:*
Added recipes for scipy, scikit-learn, shapely packages.
Plese check the README file for hosttools requirement.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rpcme** [comment]
Closing snice this went somewhere else.

**Comment by jwinarske** [comment]
@rpcme Heads up.  I provided the scikit-learn patch to Srikanth when he was working as a contractor at Toyota.  He never asked permission to distribute it.

**Comment by rpcme** [comment]
Hello @jwinarske I've acknowledged the message.  Will follow up when I know more.  FYI this PR wasn't approved to come into meta-aws.

**Comment by jwinarske** [comment]
I removed my comment after communicating with Srikanth

**Pull request closed without merging**
