### PR TITLE
scikit-learn, scipy and shapely packages

### PR DESCRIPTION
**Pull request by srikanth311**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rpcme** [comment]
Still working on verifying.  Sorry for the delay.

**Comment by rpcme** [comment]
@srikanth311 I can't force everyone to install the hosttools for all recipes across meta-aws.  can we do this as a documented requirement instead?

**Comment by srikanth311** [comment]
Closing this PR, opening new one with suggested change to README file.

**Comment by srikanth311** [comment]
Closing this PR, opening new one with suggested change to README file.

**Pull request closed without merging**
