### PR TITLE
feat: adding 2.4.0 gg recipe

### PR DESCRIPTION
**Pull request by philcali**
*Issue #, if available:*

*Description of changes:*

Attempting to add 2.4.0 GG recipes to the list of supported versions. Let me know what I need to do as pre-requisites.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rpcme** [comment]
@philcali thanks for fixing the -demo files. is it reasonable to say that if someone uses the -demo recipe they will want to always use the latest ggv2?  If so I think maybe we just maintain one.  Would like to hear thoughts on this - if you agree perhaps we change it in the context of this PR.

**Comment by hancin** [comment]
We could maintain a singular demo file and recommend people set the preferred version of greengrass they want. that would work and the docs already say that. I created several of them in case the process changed in future greengrass version.

A customer could use the demo image to try and repro an issue they're experiencing with their live devices. demo is provisioned at imaging time which can make this easier.

**Review by hancin — APPROVED** [review]
Changes look good to me. Cheers.

**Comment by rpcme** [comment]
Thank you @hancin - @philcali would you like to make that change now or in a future sprint?  I'm good either way.

**Comment by philcali** [comment]
Yeah @rpcme, I like the suggested / simplified approach. I'll treat that as an out of scope change since I currently tested these changes. I'll perform a repeat test after a refactor.

**Pull request merged**
