### PR TITLE
Add amazon-ecr-credential-helper-0.4.0 recipe

### PR DESCRIPTION
**Pull request by Minipada**
*Description of changes:*
Added the recipe [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) version 0.4.0 (last release)

*How I wrote it*
I copy pasted the description/summary from the repository. I tried my best to list licenses from the repository. You probably want to double check though, to be fully compliant.

*How I tested*
I built for qemux86-64 and I could find `/usr/bin/docker-credential-ecr-login` in the `packages-split` folder. The binary weighs 6.3M
I started a VM, ran the binary and got 
```
Usage: docker-credential-ecr-login <store|get|erase|list|version>
```
which looks good.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Minipada** [comment]
Running a docker pull, I actually get into trouble:

```
docker pull AWS_ID.dkr.ecr.us-east-1.amazonaws.com/MY_DOCKER_IMAGE:MY_DOCKER_IMAGE_TAG
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x21 pc=0x7fab2590eb80]

goroutine 1 [running]:
regexp.(*Regexp).FindStringSubmatch(0xc0004d4240, 0xc000204008, 0x2c, 0x7fab25459001, 0x6bfc907b32, 0xc035e9dd8d)
	/usr/lib/go/src/regexp/regexp.go:982 +0x50
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api.ExtractRegistry(0xc000204008, 0x2c, 0x7fab26679880, 0x0, 0x0)
	/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/build/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api/client.go:48 +0xa4
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api.(*defaultClient).getAuthorizationToken(0xc00000ec60, 0xc0003261e0, 0xc, 0x0, 0xc00038e040, 0xc0004d6480)
	/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/build/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api/client.go:181 +0x284
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api.(*defaultClient).GetCredentialsByRegistryID(0xc00000ec60, 0xc0003261e0, 0xc, 0x1, 0x1, 0xc0004ec690)
	/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/build/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api/client.go:111 +0xa6
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api.(*defaultClient).GetCredentials(0xc00000ec60, 0xc0003261e0, 0x2c, 0x55aef952ea20, 0xc00000ec60, 0xc00041da68)
	/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/build/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api/client.go:94 +0x328
github.com/awslabs/amazon-ecr-credential-helper/ecr-login.ECRHelper.Get(0x55aef952fda0, 0x7fab2701b908, 0xc0003261e0, 0x2c, 0x7fab2552b832, 0xc0003261e0, 0x2c, 0x7fab260db148, 0xc0003261e0, 0x2c)
	/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/build/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/ecr.go:66 +0x3b3
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials.Get(0x55aef952f6a0, 0xc000012790, 0x55aef952ce40, 0xc00039a000, 0x55aef952ce60, 0xc00039a008, 0xc000012790, 0x10)
	/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/git-r0/build/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go:130 +0x225
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x55aef952f6a0, 0xc000012790, 0x7ffdcb7b3e56, 0x3, 0x55aef952ce40, 0xc00039a000, 0x55aef952ce60, 0xc00039a008, 0xc00041dee8, 0x7fab2540911a)
	/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/git-r0/build/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go:73 +0x1f3
github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials.Serve(0x55aef952f6a0, 0xc000012790)
	/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/git-r0/build/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go:58 +0x22a
main.main()
	/YOCTO_DIR/tmp/work/core2-64-poky-linux/amazon-ecr-credential-helper/0.4.0-r0/build/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login/main.go:45 +0x162
Error response from daemon: Get https://AWS_ID.dkr.ecr.us-east-1.amazonaws.com/v2/MY_DOCKER_IMAGE/manifests/MY_DOCKER_IMAGE_TAG: no basic auth credentials
```

I am not a go developer, but doesn't it seem like linking issue?

**Comment by Minipada** [comment]
I tried following the command here https://github.com/awslabs/amazon-ecr-credential-helper/blob/68cfee07af64dcc2a171c20eb6f3e13e9550920a/scripts/build_binary.sh#L35-L38
Last note. I tried adding those, without success:
```
CGO_ENABLED = "0"
CGO_LDFLAGS = "-s"
```

**Comment by rpcme** [comment]
@Minipada Sorry for the delay, I have been on leave.

I have not yet had the opportunity to work with this utility.  If you could move the recipe into a base directory "recipes-ecr" that would be great.  Meanwhile, if this is a runtime break, maybe post an Issue for the amazon-ecr-credential-helper repo, and then I can attempt to follow up internally?  At this exact moment, I do not know who maintains this repo internal AWS but I will find out and highlight your issue to see what the error signature might mean.

**Comment by Minipada** [comment]
@rpcme Thanks for the fast answer, I created an issue there and mentioned you as intern communication may be faster. I'd be glad to provide more details and do more testings.

**Comment by rpcme** [comment]
Thank you for doing that, @Minipada.  Let's hope that the signature is known and there is a simple remedy to the situation.

**Comment by Minipada** [comment]
Hello @rpcme, could you get any update internally?

**Pull request merged**
