### PR TITLE
fixed checksum for aarch64, armv7 and x86 (x86-64 was ok)

### PR DESCRIPTION
**Pull request by franccan**
*Description of changes:*
- fixed checksum for aarch64, armv7 and x86 (x86-64 was ok)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by franccan** [comment]
image

**Comment by franccan** [comment]
Bitbake fails as the checksum does not match for aarch64

```


NOTE: Running task 1186 of 3985 (/root/dist/meta-openembedded/meta-python/recipes-devtools/python/python3-certifi_2019.11.28.bb:do_unpack)
--
957 | NOTE: recipe kbd-2.2.0-r0: task do_patch: Started
958 | ERROR: corretto-11-bin-11.0.12.7.1-r0 do_fetch: Fetcher failure for URL: 'https://corretto.aws/downloads/resources/11.0.12.7.1/amazon-corretto-11.0.12.7.1-linux-aarch64.tar.gz;name=aarch64'. Checksum mismatch!
959 | File: '/downloads/amazon-corretto-11.0.12.7.1-linux-aarch64.tar.gz' has md5 checksum facff11c6ae8e5b9dc54cbbbddaf3dc0 when bee1464959cd48f811390b8164bd4788 was expected
960 | File: '/downloads/amazon-corretto-11.0.12.7.1-linux-aarch64.tar.gz' has sha256 checksum 3de81a85e8ddbc03045e25b2025b00c8965d9c9be44bf0eefef10773dcc33e7f when e25669eb74d6c270af303bc0d1d859dd9ff16a0288f00a9d0ba4105467fc9695 was expected
961 | If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
962 | SRC_URI[aarch64.sha256sum] = "3de81a85e8ddbc03045e25b2025b00c8965d9c9be44bf0eefef10773dcc33e7f"
963 | Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.
964 | ERROR: corretto-11-bin-11.0.12.7.1-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'https://corretto.aws/downloads/resources/11.0.12.7.1/amazon-corretto-11.0.12.7.1-linux-aarch64.tar.gz;name=aarch64')
965 | ERROR: Logfile of failure stored in: /build-output/work/aarch64-poky-linux/corretto-11-bin/11.0.12.7.1-r0/temp/log.do_fetch.32299
966 | NOTE: recipe corretto-11-bin-11.0.12.7.1-r0: task do_fetch: Failed
967 | ERROR: Task (/root/dist/meta-aws/recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb:do_fetch) failed with exit code '1'


```

**Comment by nateglims** [comment]
Thanks for the fix. However, we need to merge into master-next then release into master.

**Comment by nateglims** [comment]
To fix some underlying merge issues, I had to make some changes to `master-next` and cherry-pick your change onto it. #250 will merge this instead.

**Pull request closed without merging**
