### PR TITLE
Fix Amazon Corretto 11 SRC_URI for armv7

### PR DESCRIPTION
**Pull request by QuantumLove**
*Issue # N/A:*

Hey guys,

Found a small typo when trying to build `greengrass-bin` for rpi4!

*Description of changes:*

The SRC_URI for this arch was wrong.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rpcme** [comment]
Thank you! I can't wait until our CI is in place! I build for 64 bit on RPi 4 so I didn't catch it.  Thanks again!

**Comment by rpcme** [comment]
I pull down to relevant release branches later today.

**Comment by MartinLoeper** [comment]
@rpcme I think this patch is still missing in dunfell, isn't it?

**Comment by QuantumLove** [comment]
Correct @MartinLoeper!

**Comment by rpcme** [comment]
@MartinLoeper @QuantumLove hi there - I don't see the problem? 

If there is a problem please file an Issue - I missed the message 7 days ago because this PR is closed

**Comment by MartinLoeper** [comment]
This issue was already fixed by a recent PR that changed the SRC_URI for
the dunfell branch. Everything works for us now.

Richard Elberger ***@***.***> schrieb am Mo., 9. Aug. 2021,
12:16:

**Pull request merged**
